version: "3.8"

services:
  app:
    build: .
    container_name: salt_authentication_app
    depends_on:
      - salt_authentication_db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - fastapi_network

  salt_authentication_db:
    image: postgres:15
    container_name: salt_authentication_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

networks:
  fastapi_network:

volumes:
  pg_data:
